spring:
  jpa:
    generate-ddl: false
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
logging:
  level:
    org:
      springframework:
        web: INFO
      hibernate:
        SQL: INFO
