spring:
  jpa:
    generate-ddl: false
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baselineVersion: 0
    baselineOnMigrate: true
    locations:
      - classpath:db/migration
logging:
  level:
    org:
      springframework:
        web: INFO
      hibernate:
        SQL: INFO
